AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cogira backend - Single modular-monolith Lambda with router and multiple domain handlers

Parameters:
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
  UsersTableName:
    Type: String
    Description: Name of the DynamoDB table used to store users
    Default: UsersTable

Globals:
  Function:
    Runtime: nodejs22.x
    MemorySize: 128
    Timeout: 10
    CodeUri: ./src/
    Tracing: Active
    Environment:
      Variables:
        USERS_TABLE: !Sub '${UsersTableName}-${Environment}'
        NODE_ENV: !Ref Environment
        LOG_LEVEL: !If [IsProd, 'warn', 'info']

Conditions:
  IsProd: !Equals [!Ref Environment, 'prod']

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: Cogira API
      DefaultRouteSettings:
        ThrottlingRateLimit: 10
        ThrottlingBurstLimit: 20
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Correlation-Id
        AllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        ExposeHeaders:
          - X-Correlation-Id

  UsersDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${UsersTableName}-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: entityType
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: ByEntityType
          KeySchema:
            - AttributeName: entityType
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  CogiraFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Events:
        GetUsers:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/v1/users
            Method: GET
        PostUsers:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/v1/users
            Method: POST
        GetUserById:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/v1/users/{id}
            Method: GET
        PutUserById:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/v1/users/{id}
            Method: PUT
        PatchUserById:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/v1/users/{id}
            Method: PATCH
        DeleteUserById:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/v1/users/{id}
            Method: DELETE
        GetDocs:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/v1/docs
            Method: GET
        GetDocsProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/v1/docs/{proxy+}
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub '${UsersTableName}-${Environment}'
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Platform: node
        Target: 'node22'
        Sourcemap: false
        EntryPoints:
          - index.ts
        Format: cjs

Outputs:
  HttpApiId:
    Description: ID of the HTTP API
    Value: !Ref HttpApi
  HttpApiEndpoint:
    Description: Base URL of the HTTP API
    Value: !GetAtt HttpApi.ApiEndpoint
  UsersEndpoint:
    Description: Example endpoint for users routes
    Value:
      Fn::Sub:
        - '${ApiEndpoint}/api/v1/users'
        - { ApiEndpoint: !GetAtt HttpApi.ApiEndpoint }
  FunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt CogiraFunction.Arn
  Environment:
    Description: Deployment environment
    Value: !Ref Environment
