AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Single modular-monolith Lambda with router and three domain handlers

Parameters:
  UsersTableName:
    Type: String
    Description: Name of the DynamoDB table used to store users
    Default: UsersTable

Globals:
  Function:
    Runtime: nodejs22.x
    MemorySize: 128
    Timeout: 10
    CodeUri: ./src/
    Tracing: Active
    Environment:
      Variables:
        USERS_TABLE: !Ref UsersTableName

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: Modular monolith API
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS

  UsersDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref UsersTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  ModularMonolith:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Events:
        GetUsers:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /users
            Method: GET
        PostUsers:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /users
            Method: POST
        GetUserById:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /users/{id}
            Method: GET
        PutUserById:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /users/{id}
            Method: PUT
        PatchUserById:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /users/{id}
            Method: PATCH
        DeleteUserById:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /users/{id}
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTableName
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Platform: node
        Target: "node22"
        Sourcemap: false
        EntryPoints:
          - index.ts
        Format: cjs

Outputs:
  HttpApiId:
    Description: ID of the HTTP API
    Value: !Ref HttpApi
  HttpApiEndpoint:
    Description: Base URL of the HTTP API
    Value: !GetAtt HttpApi.ApiEndpoint
  UsersEndpoint:
    Description: Example endpoint for users routes
    Value:
      Fn::Sub:
        - "${ApiEndpoint}/users"
        - { ApiEndpoint: !GetAtt HttpApi.ApiEndpoint }
