version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - python3 -m pip install --upgrade pip
      - python3 -m pip install --user aws-sam-cli
      - export PATH="$PATH:/root/.local/bin"
      - sam --version
  pre_build:
    commands:
      - sam validate
  build:
    commands:
      - echo "Building with CONFIG_ENV=${ENV:-dev}"
      - make build CONFIG_ENV=${ENV:-dev}
artifacts:
  files:
    - template.yaml
    - samconfig.toml
    - .aws-sam/**/*
  discard-paths: no

