AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: "Path-aware CI for multi-stack (generic function worker + ddb layer worker)"

Parameters:
  RepoName:
    Type: String
    Default: cogira-backend
  BranchName:
    Type: String
    Default: main
  ProjectPrefix:
    Type: String
    Default: cogira
  CiEnv:
    Type: String
    Default: dev
    Description: "ENV passed to root Makefile (loads env/<ENV>.env)"

Mappings:
  Images:
    Standard:
      Image: "aws/codebuild/standard:7.0"

Resources:
  # Optional helper param (reference only)
  RepoArn:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${ProjectPrefix}/ci/repo-arn/${RepoName}"
      Type: String
      Value: !Sub "arn:${AWS::Partition}:codecommit:${AWS::Region}:${AWS::AccountId}:${RepoName}"
      Description: "Stored for reference only."

  ############################################################
  # Roles
  ############################################################
  EventsToCodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectPrefix}-ci-events-startbuild"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: events.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StartDispatcher
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: codebuild:StartBuild
                Resource:
                  - !GetAtt CiDispatchProject.Arn
                  - !GetAtt CiDeployerProject.Arn

  CiDispatchRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectPrefix}-ci-dispatch-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: codebuild.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Logs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: DiffAndTrigger
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # read PR + diffs + clone buildspec from repo
              - Effect: Allow
                Action:
                  - codecommit:GetDifferences
                  - codecommit:GetCommit
                  - codecommit:GetRepository
                  - codecommit:GetPullRequest
                  - codecommit:GitPull
                Resource: !Sub "arn:${AWS::Partition}:codecommit:${AWS::Region}:${AWS::AccountId}:${RepoName}"
              # start worker builds
              - Effect: Allow
                Action: codebuild:StartBuild
                Resource:
                  - !GetAtt CiDdbLayerProject.Arn
                  - !GetAtt CiFunctionWorkerProject.Arn

  CiWorkerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectPrefix}-ci-worker-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: codebuild.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Logs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: CodeCommitRead
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - codecommit:GitPull
                  - codecommit:GetRepository
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                Resource: !Sub "arn:${AWS::Partition}:codecommit:${AWS::Region}:${AWS::AccountId}:${RepoName}"

  ############################################################
  # CodeBuild projects
  ############################################################
  CiDispatchProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectPrefix}-ci-dispatch"
      ServiceRole: !GetAtt CiDispatchRole.Arn
      Artifacts: { Type: NO_ARTIFACTS }
      Source:
        Type: CODECOMMIT
        Location: !Sub "https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${RepoName}"
        GitCloneDepth: 1
        BuildSpec: "pipeline/ci-dispatcher.yml" # lives in repo
      Environment:
        Type: LINUX_CONTAINER
        Image: !FindInMap [Images, Standard, Image]
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - { Name: REPO_NAME, Value: !Ref RepoName }
          - { Name: BRANCH, Value: !Ref BranchName }
          - { Name: CI_ENV, Value: !Ref CiEnv }
          - { Name: CI_DDB, Value: !Ref CiDdbLayerProject }
          - { Name: CI_FUNC, Value: !Ref CiFunctionWorkerProject }
      TimeoutInMinutes: 10
      QueuedTimeoutInMinutes: 10
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED

  # Fixed worker for the shared DDB layer
  CiDdbLayerProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectPrefix}-ci-layers-ddb"
      ServiceRole: !GetAtt CiWorkerRole.Arn
      Artifacts: { Type: NO_ARTIFACTS }
      Source:
        Type: CODECOMMIT
        Location: !Sub "https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${RepoName}"
        GitCloneDepth: 1
        BuildSpec: "pipeline/ci-worker.yml" # shared worker buildspec
      Environment:
        Type: LINUX_CONTAINER
        Image: !FindInMap [Images, Standard, Image]
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - { Name: ENV, Value: !Ref CiEnv }
          - { Name: MAKE_TARGET, Value: "ci-ddb-layer" }
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED

  # Generic worker for ANY function under functions/<name>/
  CiFunctionWorkerProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectPrefix}-ci-functions-generic"
      ServiceRole: !GetAtt CiWorkerRole.Arn
      Artifacts: { Type: NO_ARTIFACTS }
      Source:
        Type: CODECOMMIT
        Location: !Sub "https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${RepoName}"
        GitCloneDepth: 1
        BuildSpec: "pipeline/ci-worker.yml" # shared worker buildspec
      Environment:
        Type: LINUX_CONTAINER
        Image: !FindInMap [Images, Standard, Image]
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - { Name: ENV, Value: !Ref CiEnv }
          - { Name: MAKE_TARGET, Value: "ci-function" } # function name injected per-build
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED

  ############################################################
  # PR events -> dispatcher (pins buildspec to destination commit)
  ############################################################
  PullRequestCI:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${ProjectPrefix}-ci-pr"
      Description: !Sub "Trigger CI on CodeCommit PR create/update to ${BranchName}"
      EventPattern:
        source: ["aws.codecommit"]
        detail-type: ["CodeCommit Pull Request State Change"]
        resources:
          - !Sub "arn:${AWS::Partition}:codecommit:${AWS::Region}:${AWS::AccountId}:${RepoName}"
        detail:
          event:
            - pullRequestCreated
            - pullRequestSourceBranchUpdated
            - pullRequestReopened
          destinationReference:
            - !Sub "refs/heads/${BranchName}"
      Targets:
        - Id: Dispatch
          Arn: !GetAtt CiDispatchProject.Arn
          RoleArn: !GetAtt EventsToCodeBuildRole.Arn
          InputTransformer:
            InputPathsMap:
              pr: $.detail.pullRequestId
              srcCommit: $.detail.sourceCommit
              dstCommit: $.detail.destinationCommit
            InputTemplate: |
              {
                "sourceVersion": "<dstCommit>",
                "environmentVariablesOverride": [
                  {"name":"PR_ID","value":"<pr>","type":"PLAINTEXT"},
                  {"name":"SOURCE_COMMIT","value":"<srcCommit>","type":"PLAINTEXT"},
                  {"name":"DESTINATION_COMMIT","value":"<dstCommit>","type":"PLAINTEXT"}
                ]
              }

  CiDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectPrefix}-ci-deployer-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: codebuild.amazonaws.com }
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Logs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  [
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:PutLogEvents",
                  ]
                Resource: "*"
        - PolicyName: CodeCommitRead
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  [
                    "codecommit:GitPull",
                    "codecommit:GetRepository",
                    "codecommit:GetCommit",
                    "codecommit:GetDifferences",
                  ]
                Resource: !Sub "arn:${AWS::Partition}:codecommit:${AWS::Region}:${AWS::AccountId}:${RepoName}"
        - PolicyName: CloudFormationDeploy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:Describe*
                Resource: !Sub "arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${ProjectPrefix}-*/*"
        - PolicyName: SamArtifactsS3
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: ["s3:PutObject", "s3:GetObject", "s3:ListBucket"]
                Resource: "*"

  CiDeployerProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${ProjectPrefix}-ci-deploy"
      ServiceRole: !GetAtt CiDeployerRole.Arn
      Artifacts: { Type: NO_ARTIFACTS }
      Source:
        Type: CODECOMMIT
        Location: !Sub "https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${RepoName}"
        GitCloneDepth: 1
        BuildSpec: "pipeline/ci-deploy.yml"
      Environment:
        Type: LINUX_CONTAINER
        Image: !FindInMap [Images, Standard, Image]
        ComputeType: BUILD_GENERAL1_SMALL
      TimeoutInMinutes: 20
      LogsConfig:
        CloudWatchLogs: { Status: ENABLED }

  MainBranchCD:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${ProjectPrefix}-cd-main"
      Description: "Auto-deploy on merge to main"
      EventPattern:
        source: ["aws.codecommit"]
        detail-type: ["CodeCommit Repository State Change"]
        resources:
          - !Sub "arn:${AWS::Partition}:codecommit:${AWS::Region}:${AWS::AccountId}:${RepoName}"
        detail:
          event: ["referenceUpdated"]
          referenceType: ["branch"]
          referenceName: ["${BranchName}"] # main by default
      Targets:
        - Id: Deployer
          Arn: !GetAtt CiDeployerProject.Arn
          RoleArn: !GetAtt EventsToCodeBuildRole.Arn
          InputTransformer:
            InputPathsMap:
              commit: $.detail.commitId
              old: $.detail.oldCommitId
              refName: $.detail.referenceName
            InputTemplate: |
              {
                "sourceVersion": "<commit>",
                "environmentVariablesOverride": [
                  {"name":"COMMIT_ID","value":"<commit>","type":"PLAINTEXT"},
                  {"name":"OLD_COMMIT","value":"<old>","type":"PLAINTEXT"},
                  {"name":"REF","value":"refs/heads/<refName>","type":"PLAINTEXT"},
                  {"name":"ENV","value":"${CiEnv}","type":"PLAINTEXT"},
                  {"name":"REPO_NAME","value":"${RepoName}","type":"PLAINTEXT"},
                  {"name":"PROJECT_PREFIX","value":"${ProjectPrefix}","type":"PLAINTEXT"}
                ]
              }

Outputs:
  DispatchProject: { Value: !Ref CiDispatchProject }
  WorkerDdb: { Value: !Ref CiDdbLayerProject }
  WorkerFunction: { Value: !Ref CiFunctionWorkerProject }
