AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Minimal hello-lambda function with TypeScript and esbuild

Parameters:
  DDBLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cogira/layers/ddb

Globals:
  Function:
    Runtime: nodejs22.x
    MemorySize: 128
    Timeout: 5
    CodeUri: ./src/
    Layers:
      - !Ref DDBLayerArn

Resources:
  HelloLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Events:
        HelloApi:
          Type: HttpApi
          Properties:
            Path: /hello-lambda
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: false
        EntryPoints:
          - index.ts
        Format: esm
        OutExtension:
          - .js=.mjs
